<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('code' => 'US', 'name' => 'United States', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MX', 'name' => 'Mexico', 'language' => 'es', 'currency' => 'MXN'),
            array('code' => 'CA', 'name' => 'Canada', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AS', 'name' => 'American Samoa', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AD', 'name' => 'Andorra', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AI', 'name' => 'Anguilla', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AQ', 'name' => 'Antarctica', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AG', 'name' => 'Antigua and/or Barbuda', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AR', 'name' => 'Argentina', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'AM', 'name' => 'Armenia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AW', 'name' => 'Aruba', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AU', 'name' => 'Australia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AT', 'name' => 'Austria', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AZ', 'name' => 'Azerbaijan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BS', 'name' => 'Bahamas', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BH', 'name' => 'Bahrain', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BD', 'name' => 'Bangladesh', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BB', 'name' => 'Barbados', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BY', 'name' => 'Belarus', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BE', 'name' => 'Belgium', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BZ', 'name' => 'Belize', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BM', 'name' => 'Bermuda', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BT', 'name' => 'Bhutan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BO', 'name' => 'Bolivia', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BV', 'name' => 'Bouvet Island', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BR', 'name' => 'Brazil', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IO', 'name' => 'British lndian Ocean Territory', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BN', 'name' => 'Brunei Darussalam', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'BG', 'name' => 'Bulgaria', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'KH', 'name' => 'Cambodia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'KY', 'name' => 'Cayman Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CL', 'name' => 'Chile', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'CN', 'name' => 'China', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CX', 'name' => 'Christmas Island', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CO', 'name' => 'Colombia', 'language' => 'es', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CK', 'name' => 'Cook Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CR', 'name' => 'Costa Rica', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CU', 'name' => 'Cuba', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'CY', 'name' => 'Cyprus', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CZ', 'name' => 'Czech Republic', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'DK', 'name' => 'Denmark', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'DM', 'name' => 'Dominica', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'DO', 'name' => 'República Dominicana', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'TP', 'name' => 'East Timor', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'EC', 'name' => 'Ecuador', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'SV', 'name' => 'El Salvador', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'EE', 'name' => 'Estonia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FO', 'name' => 'Faroe Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FJ', 'name' => 'Fiji', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FI', 'name' => 'Finland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FR', 'name' => 'France', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FX', 'name' => 'France, Metropolitan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GF', 'name' => 'French Guiana', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PF', 'name' => 'French Polynesia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TF', 'name' => 'French Southern Territories', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GE', 'name' => 'Georgia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'DE', 'name' => 'Germany', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GI', 'name' => 'Gibraltar', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GR', 'name' => 'Greece', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GL', 'name' => 'Greenland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GD', 'name' => 'Grenada', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GP', 'name' => 'Guadeloupe', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GU', 'name' => 'Guam', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GT', 'name' => 'Guatemala', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'GY', 'name' => 'Guyana', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'HT', 'name' => 'Haiti', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'HN', 'name' => 'Honduras', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'HK', 'name' => 'Hong Kong', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'HU', 'name' => 'Hungary', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IS', 'name' => 'Iceland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IN', 'name' => 'India', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'ID', 'name' => 'Indonesia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IE', 'name' => 'Ireland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IL', 'name' => 'Israel', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'IT', 'name' => 'Italy', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'JM', 'name' => 'Jamaica', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'JP', 'name' => 'Japan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'KR', 'name' => 'Korea, Republic of', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'LV', 'name' => 'Latvia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'LI', 'name' => 'Liechtenstein', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'LT', 'name' => 'Lithuania', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'LU', 'name' => 'Luxembourg', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MO', 'name' => 'Macau', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MK', 'name' => 'Macedonia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MY', 'name' => 'Malaysia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MT', 'name' => 'Malta', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MH', 'name' => 'Marshall Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MQ', 'name' => 'Martinique', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TY', 'name' => 'Mayotte', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'FM', 'name' => 'Micronesia, Federated States of', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MD', 'name' => 'Moldova, Republic of', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MC', 'name' => 'Monaco', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MN', 'name' => 'Mongolia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MS', 'name' => 'Montserrat', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MM', 'name' => 'Myanmar', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NR', 'name' => 'Nauru', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NP', 'name' => 'Nepal', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NL', 'name' => 'Netherlands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AN', 'name' => 'Netherlands Antilles', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NC', 'name' => 'New Caledonia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NZ', 'name' => 'New Zealand', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NI', 'name' => 'Nicaragua', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'NU', 'name' => 'Niue', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NF', 'name' => 'Norfork Island', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'MP', 'name' => 'Northern Mariana Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'NO', 'name' => 'Norway', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'OM', 'name' => 'Oman', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PW', 'name' => 'Palau', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PA', 'name' => 'Panama', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'PG', 'name' => 'Papua New Guinea', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PY', 'name' => 'Paraguay', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'PE', 'name' => 'Peru', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'PH', 'name' => 'Philippines', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PN', 'name' => 'Pitcairn', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PL', 'name' => 'Poland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PT', 'name' => 'Portugal', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PR', 'name' => 'Puerto Rico', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'QA', 'name' => 'Qatar', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'RE', 'name' => 'Reunion', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'RO', 'name' => 'Romania', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'RU', 'name' => 'Russian Federation', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'LC', 'name' => 'Saint Lucia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'WS', 'name' => 'Samoa', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SM', 'name' => 'San Marino', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'RS', 'name' => 'Serbia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SG', 'name' => 'Singapore', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SK', 'name' => 'Slovakia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SI', 'name' => 'Slovenia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SB', 'name' => 'Solomon Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'ES', 'name' => 'España', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'LK', 'name' => 'Sri Lanka', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SH', 'name' => 'St. Helena', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'PM', 'name' => 'St. Pierre and Miquelon', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SR', 'name' => 'Suriname', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SE', 'name' => 'Sweden', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'CH', 'name' => 'Switzerland', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'SY', 'name' => 'Syrian Arab Republic', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TW', 'name' => 'Taiwan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TJ', 'name' => 'Tajikistan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TH', 'name' => 'Thailand', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TK', 'name' => 'Tokelau', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TO', 'name' => 'Tonga', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TT', 'name' => 'Trinidad and Tobago', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TR', 'name' => 'Turkey', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TM', 'name' => 'Turkmenistan', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TC', 'name' => 'Turks and Caicos Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'TV', 'name' => 'Tuvalu', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'UA', 'name' => 'Ukraine', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'AE', 'name' => 'United Arab Emirates', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'GB', 'name' => 'United Kingdom', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'UM', 'name' => 'United States minor outlying islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'UY', 'name' => 'Uruguay', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'VU', 'name' => 'Vanuatu', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'VA', 'name' => 'Vatican City State', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'VE', 'name' => 'Venezuela', 'language' => 'es', 'currency' => 'USD'),
            array('code' => 'VN', 'name' => 'Vietnam', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'VG', 'name' => 'Virgin Islands (British)', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'EH', 'name' => 'Western Sahara', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'YE', 'name' => 'Yemen', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'YU', 'name' => 'Yugoslavia', 'language' => 'en', 'currency' => 'USD'),
            array('code' => 'ZR', 'name' => 'Zaire', 'language' => 'en', 'currency' => 'USD')
        );
        DB::table('countries')->insert($countries);
    }
}
