<?php

use Illuminate\Database\Seeder;

class StatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    //	DB:table('states')->delete();
        $states = array(
            array( "country" => "US", "code" => "AL", "name" => "Alabama" ),
            array( "country" => "US", "code" => "AK", "name" => "Alaska" ), 
            array( "country" => "US", "code" => "AS", "name" => "American Samoa" ),
            array( "country" => "US", "code" => "AZ", "name" => "Arizona" ),
            array( "country" => "US", "code" => "AR", "name" => "Arkansas" ),
            array( "country" => "US", "code" => "CA", "name" => "California" ),
            array( "country" => "US", "code" => "CO", "name" => "Colorado" ),
            array( "country" => "US", "code" => "CT", "name" => "Connecticut" ),
            array( "country" => "US", "code" => "DE", "name" => "Delaware" ),
            array( "country" => "US", "code" => "DC", "name" => "District of Columbia" ),
            array( "country" => "US", "code" => "FM", "name" => "Federated States of Micronesia" ),
            array( "country" => "US", "code" => "FL", "name" => "Florida" ),
            array( "country" => "US", "code" => "GA", "name" => "Georgia" ),
            array( "country" => "US", "code" => "GU", "name" => "Guam" ),
            array( "country" => "US", "code" => "HI", "name" => "Hawaii" ),
            array( "country" => "US", "code" => "ID", "name" => "Idaho" ),
            array( "country" => "US", "code" => "IL", "name" => "Illinois" ),
            array( "country" => "US", "code" => "IN", "name" => "Indiana" ), 
            array( "country" => "US", "code" => "IA", "name" => "Iowa" ),
            array( "country" => "US", "code" => "KS", "name" => "Kansas" ),
            array( "country" => "US", "code" => "KY", "name" => "Kentucky" ),
            array( "country" => "US", "code" => "LA", "name" => "Louisiana" ),
            array( "country" => "US", "code" => "ME", "name" => "Maine" ),
            array( "country" => "US", "code" => "MH", "name" => "Marshall Islands" ),
            array( "country" => "US", "code" => "MD", "name" => "Maryland" ),
            array( "country" => "US", "code" => "MA", "name" => "Massachusetts" ),
            array( "country" => "US", "code" => "MI", "name" => "Michigan" ), 
            array( "country" => "US", "code" => "MN", "name" => "Minnesota" ), 
            array( "country" => "US", "code" => "MS", "name" => "Mississippi" ),
            array( "country" => "US", "code" => "MO", "name" => "Missouri" ),
            array( "country" => "US", "code" => "MT", "name" => "Montana" ),
            array( "country" => "US", "code" => "NE", "name" => "Nebraska" ),
            array( "country" => "US", "code" => "NV", "name" => "Nevada" ),
            array( "country" => "US", "code" => "NH", "name" => "New Hampshire" ),
            array( "country" => "US", "code" => "NJ", "name" => "New Jersey" ),
            array( "country" => "US", "code" => "NM", "name" => "New Mexico" ),
            array( "country" => "US", "code" => "NY", "name" => "New York" ),
            array( "country" => "US", "code" => "NC", "name" => "North Carolina" ),
            array( "country" => "US", "code" => "ND", "name" => "North Dakota" ),
            array( "country" => "US", "code" => "MP", "name" => "Northern Mariana Islands" ),
            array( "country" => "US", "code" => "OH", "name" => "Ohio" ),
            array( "country" => "US", "code" => "OK", "name" => "Oklahoma" ),
            array( "country" => "US", "code" => "OR", "name" => "Oregon" ),
            array( "country" => "US", "code" => "PW", "name" => "Palau" ),
            array( "country" => "US", "code" => "PA", "name" => "Pennsylvania" ),
            array( "country" => "US", "code" => "PR", "name" => "Puerto Rico" ),
            array( "country" => "US", "code" => "RI", "name" => "Rhode Island" ),
            array( "country" => "US", "code" => "SC", "name" => "South Carolina" ),
            array( "country" => "US", "code" => "SD", "name" => "South Dakota" ),
            array( "country" => "US", "code" => "TN", "name" => "Tennessee" ),
            array( "country" => "US", "code" => "TX", "name" => "Texas" ),
            array( "country" => "US", "code" => "UT", "name" => "Utah" ),
            array( "country" => "US", "code" => "VT", "name" => "Vermont" ),
            array( "country" => "US", "code" => "VI", "name" => "Virgin Islands" ),
            array( "country" => "US", "code" => "VA", "name" => "Virginia" ),
            array( "country" => "US", "code" => "WA", "name" => "Washington" ),
            array( "country" => "US", "code" => "WV", "name" => "West Virginia" ),
            array( "country" => "US", "code" => "WI", "name" => "Wisconsin" ),
            array( "country" => "US", "code" => "WY", "name" => "Wyoming" ),
            array( "country" => "US", "code" => "AE", "name" => "Armed Forces Europe, the Middle East, and Canada" ),
            array( "country" => "US", "code" => "AP", "name" => "Armed Forces Pacific" ),
            array( "country" => "US", "code" => "AA", "name" => "Armed Forces Americas (except Canada)" ),         
            array( "country" => "MX", "code" => "AGS", "name"=> "Aguascalientes" ),
            array( "country" => "MX", "code" => "BCN", "name"=> "Baja California" ),
            array( "country" => "MX", "code" => "BCS", "name"=> "Baja California Sur" ),
            array( "country" => "MX", "code" => "CAMP", "name"=> "Campeche" ),
            array( "country" => "MX", "code" => "CHIS", "name"=> "Chiapas" ),
            array( "country" => "MX", "code" => "CHIH", "name"=> "Chihuahua" ),
            array( "country" => "MX", "code" => "COAH", "name"=> "Coahuila de Zaragoza" ),
            array( "country" => "MX", "code" => "COL", "name"=> "Colima" ),
            array( "country" => "MX", "code" => "DF", "name"=> "Distrito Federal" ),
            array( "country" => "MX", "code" => "DGO", "name"=> "Durango" ),
            array( "country" => "MX", "code" => "GTO", "name"=> "Guanajuato" ),
            array( "country" => "MX", "code" => "GRO", "name"=> "Guerrero" ),
            array( "country" => "MX", "code" => "HGO", "name"=> "Hidalgo" ),
            array( "country" => "MX", "code" => "JAL", "name"=> "Jalisco" ),
            array( "country" => "MX", "code" => "MEX", "name"=> "México" ),
            array( "country" => "MX", "code" => "MICH","name"=> "Michoacán de Ocampo" ),
            array( "country" => "MX", "code" => "MOR", "name"=> "Morelos" ),
            array( "country" => "MX", "code" => "NAY", "name"=> "Nayarit" ),
            array( "country" => "MX", "code" => "NL", "name"=> "Nuevo León" ),
            array( "country" => "MX", "code" => "OAX", "name"=> "Oaxaca" ),
            array( "country" => "MX", "code" => "PUE", "name"=> "Puebla" ),
            array( "country" => "MX", "code" => "QRO","name"=> "Querétaro" ),
            array( "country" => "MX", "code" => "QR", "name"=> "Quintana Roo" ),
            array( "country" => "MX", "code" => "SLP", "name"=> "San Luis Potosí" ),
            array( "country" => "MX", "code" => "SIN", "name"=> "Sinaloa" ),
            array( "country" => "MX", "code" => "SON", "name"=> "Sonora" ),
            array( "country" => "MX", "code" => "TAB", "name"=> "Tabasco" ),
            array( "country" => "MX", "code" => "TAMPS", "name"=> "Tamaulipas" ),
            array( "country" => "MX", "code" => "TLAX", "name"=> "Tlaxcala" ),
            array( "country" => "MX", "code" => "VER", "name"=> "Veracruz de Ignacio de la Llave" ),
            array( "country" => "MX", "code" => "YUC", "name"=> "Yucatán" ),
            array( "country" => "MX", "code" => "ZAC", "name"=> "Zacatecas" ),
            array( "country" => "CA", "code"=>"AB", "name"=>"Alberta"),
			array( "country" => "CA", "code"=>"BC", "name"=>"British Columbia"),
			array( "country" => "CA", "code"=>"LB", "name"=>"Labrador"),
			array( "country" => "CA", "code"=>"MB", "name"=>"Manitoba"),
			array( "country" => "CA", "code"=>"NB", "name"=>"New Brunswick"),
			array( "country" => "CA", "code"=>"NF", "name"=>"Newfoundland"),
			array( "country" => "CA", "code"=>"NL", "name"=>"Newfoundland & Labrador"),
			array( "country" => "CA", "code"=>"NS", "name"=>"Nova Scotia"),
			array( "country" => "CA", "code"=>"NT", "name"=>"Northwest Territories"),
			array( "country" => "CA", "code"=>"NU", "name"=>"Nunavut Territory"),
			array( "country" => "CA", "code"=>"ON", "name"=>"Ontario"),
			array( "country" => "CA", "code"=>"PE ", "name"=>"Prince Edward Island"),
			array( "country" => "CA", "code"=>"PQ", "name"=>"Quebec"),
			array( "country" => "CA", "code"=>"SK", "name"=>"Saskatchewan "),
			array( "country" => "CA", "code"=>"YT", "name"=>"Yukon Territory"),
			array( "country" => "AU", "code"=>"ACT ", "name"=>"Australian Cap. Terr."),
			array( "country" => "AU", "code"=>"NSW", "name"=>"New South Wales"),
			array( "country" => "AU", "code"=>"NT ", "name"=>"Northern Territory"),
			array( "country" => "AU", "code"=>"QLD ", "name"=>"Queensland "),
			array( "country" => "AU", "code"=>"SA", "name"=>"South Australia"),
			array( "country" => "AU", "code"=>"TAS", "name"=>"Tasmania"),
			array( "country" => "AU", "code"=>"VIC", "name"=>"Victoria"),
			array( "country" => "AU", "code"=>"WA", "name"=>"Western Australia")
        );
        
        DB::table('states')->insert($states);
    }
}
